Repository HYF-Class23/group4-hyf-rebuild, pull requests merged in 2024-02, with the labels that each got.

#13 add constrains
  planning/backlog.md
  planning/constraints.md
Labels: documentation

#14 modified user-personas.md
  planning/user-personas.md
Labels: documentation

#15 updateDefination
  .cspell.json
Labels: documentation

#17 modified development-strategy.md
  planning/development-strategy.md
Labels: documentation

#16 add communication
  .cspell.json
  planning/communication.md
Labels: documentation

#18 addmodifiedprojectDefinition
  .cspell.json
  planning/README.md
Labels: documentation

#22 updateReadMe
  .cspell.json
Labels: documentation

#21 Proj defn3
  .cspell.json
  README.md
Labels: documentation

#26 Fix bug in README.md file
  README.md
Labels: bug

#27 newfooter
  .cspell.json
  index.html
  styles/index.css
Labels: documentation

#31 modified navbar position
  index.html
  styles/index.css
Labels: development
